const express=require('express');const session=require('express-session');const bcrypt=require('bcryptjs');const Database=require('better-sqlite3');const path=require('path');const fs=require('fs');
const app=express(),PORT=Number(process.env.PORT||3000),DATA_DIR=process.env.DATA_DIR||path.join(__dirname,'data');fs.mkdirSync(DATA_DIR,{recursive:true});
const db=new Database(path.join(DATA_DIR,'neon-royale.db'));db.pragma('journal_mode=WAL');
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,username TEXT UNIQUE NOT NULL,display_name TEXT NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'player',score REAL NOT NULL DEFAULT 0,best_score REAL NOT NULL DEFAULT 0,games_played INTEGER NOT NULL DEFAULT 0,xp INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,last_active TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS history(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,game_id TEXT NOT NULL,score_delta REAL NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS audit(id INTEGER PRIMARY KEY AUTOINCREMENT,admin_id INTEGER NOT NULL,target_user_id INTEGER NOT NULL,action TEXT NOT NULL,old_score REAL NOT NULL,change_amount REAL NOT NULL,new_score REAL NOT NULL,reason TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);`);
if(process.env.ADMIN_USER&&process.env.ADMIN_PASSWORD){const u=process.env.ADMIN_USER,h=bcrypt.hashSync(process.env.ADMIN_PASSWORD,12);const e=db.prepare('SELECT id FROM users WHERE username=?').get(u);if(e)db.prepare("UPDATE users SET password_hash=?,role='admin' WHERE id=?").run(h,e.id);else db.prepare("INSERT INTO users(username,display_name,password_hash,role) VALUES(?,?,?,'admin')").run(u,'NEON Admin',h)}
app.use(express.json());app.use(session({secret:process.env.SESSION_SECRET||'change-me',resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:604800000}}));app.use(express.static(path.join(__dirname,'public')));
const GAMES=[['aztec-cascade','AZTEC CASCADE','🗿','REELS','reel'],['temple-wheel','TEMPLE WHEEL','🎡','SPECIAL','special'],['golden-cards','GOLDEN CARDS','🃏','ARCADE','arcade'],['aztec-dice','AZTEC DICE','🎲','ARCADE','arcade'],['emerald-match','EMERALD MATCH','💎','ARCADE','arcade'],['temple-run','TEMPLE RUN','🏃','ARCADE','arcade'],['relic-hunt','RELIC HUNT','🏺','SPECIAL','special'],['serpent-memory','SERPENT MEMORY','🐍','ARCADE','arcade'],['golden-drop','GOLDEN DROP','🪙','ARCADE','arcade'],['temple-boss','TEMPLE BOSS','👹','SPECIAL','special']].map(x=>({id:x[0],name:x[1],icon:x[2],mode:x[3],category:x[4]}));
const pub=u=>({id:u.id,username:u.username,displayName:u.display_name,role:u.role,score:u.score,bestScore:u.best_score,gamesPlayed:u.games_played,xp:u.xp});
const login=(req,res,next)=>{if(!req.session.userId)return res.status(401).json({error:'LOGIN_REQUIRED'});const u=db.prepare('SELECT * FROM users WHERE id=?').get(req.session.userId);if(!u)return res.status(401).json({error:'LOGIN_REQUIRED'});req.user=u;next()};const admin=(req,res,next)=>login(req,res,()=>req.user.role==='admin'?next():res.status(403).json({error:'ADMIN_REQUIRED'}));
app.get('/health',(q,s)=>s.json({ok:true}));
app.post('/api/register',(q,s)=>{const username=String(q.body.username||'').trim(),displayName=String(q.body.displayName||'').trim(),password=String(q.body.password||'');if(!/^[A-Za-z0-9_]{3,24}$/.test(username))return s.status(400).json({error:'USERNAME_INVALID'});if(displayName.length<1||displayName.length>40)return s.status(400).json({error:'DISPLAY_NAME_INVALID'});if(password.length<6)return s.status(400).json({error:'PASSWORD_TOO_SHORT'});if(db.prepare('SELECT id FROM users WHERE username=?').get(username))return s.status(409).json({error:'USERNAME_EXISTS'});const r=db.prepare('INSERT INTO users(username,display_name,password_hash) VALUES(?,?,?)').run(username,displayName,bcrypt.hashSync(password,12));q.session.userId=r.lastInsertRowid;s.json({user:pub(db.prepare('SELECT * FROM users WHERE id=?').get(r.lastInsertRowid))})});
app.post('/api/login',(q,s)=>{const u=db.prepare('SELECT * FROM users WHERE username=?').get(String(q.body.username||'').trim());if(!u||!bcrypt.compareSync(String(q.body.password||''),u.password_hash))return s.status(401).json({error:'INVALID_LOGIN'});q.session.userId=u.id;db.prepare('UPDATE users SET last_active=CURRENT_TIMESTAMP WHERE id=?').run(u.id);s.json({user:pub(db.prepare('SELECT * FROM users WHERE id=?').get(u.id))})});
app.post('/api/logout',(q,s)=>q.session.destroy(()=>s.json({ok:true})));app.get('/api/me',login,(q,s)=>s.json({user:pub(q.user)}));app.get('/api/games',login,(q,s)=>s.json({games:GAMES}));
app.post('/api/games/:id/play',login,(q,s)=>{if(!GAMES.some(g=>g.id===q.params.id))return s.status(404).json({error:'GAME_NOT_FOUND'});const reward=[10,25,50,100,250,500][Math.floor(Math.random()*6)];const u=q.user,newScore=u.score+reward;db.prepare('UPDATE users SET score=?,best_score=?,games_played=games_played+1,xp=xp+?,last_active=CURRENT_TIMESTAMP WHERE id=?').run(newScore,Math.max(u.best_score,reward),Math.max(1,Math.floor(reward/10)),u.id);db.prepare('INSERT INTO history(user_id,game_id,score_delta) VALUES(?,?,?)').run(u.id,q.params.id,reward);s.json({user:pub(db.prepare('SELECT * FROM users WHERE id=?').get(u.id)),reward})});
app.get('/api/history',login,(q,s)=>s.json({history:db.prepare('SELECT game_id,score_delta,created_at FROM history WHERE user_id=? ORDER BY id DESC LIMIT 50').all(q.user.id)}));app.get('/api/leaderboard',login,(q,s)=>s.json({players:db.prepare("SELECT display_name name,score,xp FROM users WHERE role='player' ORDER BY score DESC LIMIT 20").all()}));
app.get('/api/admin/me',admin,(q,s)=>s.json({ok:true,user:pub(q.user)}));app.post('/api/admin/logout',admin,(q,s)=>q.session.destroy(()=>s.json({ok:true})));app.get('/api/admin/dashboard',admin,(q,s)=>s.json({stats:{players:db.prepare("SELECT COUNT(*) n FROM users WHERE role='player'").get().n,gamesPlayed:db.prepare('SELECT COUNT(*) n FROM history').get().n,totalScore:db.prepare("SELECT COALESCE(SUM(score),0) n FROM users WHERE role='player'").get().n}}));app.get('/api/admin/players',admin,(q,s)=>s.json({players:db.prepare("SELECT id,username,display_name,score,best_score,games_played,xp,last_active FROM users WHERE role='player' ORDER BY id DESC").all()}));
app.post('/api/admin/players/:id/score',admin,(q,s)=>{const id=Number(q.params.id),mode=String(q.body.mode||''),amount=Number(q.body.amount),reason=String(q.body.reason||'').trim();if(!['add','remove','set'].includes(mode)||!Number.isFinite(amount)||amount<0||!reason)return s.status(400).json({error:'INVALID_INPUT'});const p=db.prepare("SELECT * FROM users WHERE id=? AND role='player'").get(id);if(!p)return s.status(404).json({error:'PLAYER_NOT_FOUND'});const next=mode==='add'?p.score+amount:mode==='remove'?Math.max(0,p.score-amount):amount,change=next-p.score;const tx=db.transaction(()=>{db.prepare('UPDATE users SET score=? WHERE id=?').run(next,id);db.prepare('INSERT INTO audit(admin_id,target_user_id,action,old_score,change_amount,new_score,reason) VALUES(?,?,?,?,?,?,?)').run(q.user.id,id,mode,p.score,change,next,reason)});tx();s.json({ok:true})});app.get('/api/admin/logs',admin,(q,s)=>s.json({logs:db.prepare('SELECT a.*,ad.username admin_username,t.username target_username FROM audit a JOIN users ad ON ad.id=a.admin_id JOIN users t ON t.id=a.target_user_id ORDER BY a.id DESC LIMIT 200').all()}));
app.get('/admin',(q,s)=>s.sendFile(path.join(__dirname,'public','admin.html')));app.get('*',(q,s)=>q.path.startsWith('/api/')?s.status(404).json({error:'NOT_FOUND'}):s.sendFile(path.join(__dirname,'public','index.html')));app.listen(PORT,'0.0.0.0',()=>console.log(`NEON ROYALE -> http://localhost:${PORT}`));
